version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gates_of_egypt
    depends_on:
      - db
    environment:
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - gates-of-egypt

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres_db
    environment:
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gates-of-egypt

volumes:
  pgdata:

networks:
  gates-of-egypt:
